### ISSUE TITLE
is this needed now that there's `git replace --graft`

### ISSUE THREAD

**Issue by graingert** [MarkLodato/git-reparent#5]
https://git-scm.com/docs/git-replace#Documentation/git-replace.txt---graftltcommitgtltparentgt82308203

@MarkLodato ^

**Comment by MarkLodato** [comment]
No. From the docs (emphasis added):

> `--graft <commit> [<parent>…​]`
> A new commit is created with the same content as `<commit>` except that its parents will be `[<parent>…​]` instead of `<commit>`'s parents. **A replacement ref is then created to replace `<commit>` with the newly created commit.**

Both commands do the first sentence, but they differ on the second.

`git reparent` creates a new commit that mirrors HEAD then, unless `--no-reset` is given, does a `git reset` to point the current HEAD to the new commit. This is equivalent to doing a `git rebase` to include the new commit instead of the old one, with all the benefits and drawbacks to a rebase.

`git replace --graft` also creates a new commit that mirrors another commit, but then it creates a "replacement ref" that affects all references to the specified commit. In other words, if there are two branches that both reference `<commit>`, then they will *all* act as though the new parents of that commit are `[<parent>...]`.

I encourage you to set up a toy repository to test the difference. I recommend the following setup:

```
A -- B -- C (master) -- D (feature-branch)
```

First check out `master`, do a `git reparent -p A`, and see what the effect is on `master` and `feature-branch`. Then recreate the repo and do the same with`git replace --graft HEAD A`.

Unless I'm mistaken, git-reparent will result in:

```
A -- C' (master)
 \-- B -- C -- (feature-branch)
```

While git-replace will result in:

```
A -- C' (master) -- D (feature-branch)
```

**Comment by graingert** [comment]
@MarkLodato ah, brilliant. Thank you for the detailed explanation

**Comment by MarkLodato** [comment]
You're welcome. :) And please do try that example, in case my explanation was incorrect!
